### ISSUE TITLE
Publish clang-tidy 13.0.0

### ISSUE THREAD

**Issue by tristan0x** [ssciwr/clang-tidy-wheel#16]
My research project at EPFL is using LLVM 13.0.0 internally. Would it be possible to publish this version of clang-tidy on Pypi once #11 and #12 have been solved?

**Comment by renefritze** [comment]
That should be no problem :+1:  (unless we indirectly depend on some new-in-14 internals now)

**Comment by renefritze** [comment]
https://pypi.org/project/clang-tidy/13.0.1.1/

**Comment by tristan0x** [comment]
Thank you very much @renefritze
