### ISSUE TITLE
Typo in the clang-tidy Pypi project page

### ISSUE THREAD

**Issue by tristan0x** [ssciwr/clang-tidy-wheel#17]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/368123/180142225-ab6b3bdc-2b01-4315-941b-f73c5b611377.png">

Taken from https://clang.llvm.org/extra/clang-tidy/ :
```
clang-tidy is a clang-based C++ “linter” tool.
```

**Comment by renefritze** [comment]
Thanks for the heads-up @tristan0x

Looks like I didn't grep for capitalizations of `format` :upside_down_face: 

#18 fixes our side of the problem.
The change on pypi should happen when a new version is uploaded. I'm going to keep this open so I'll remember to check if that really happened.

**Comment by renefritze** [comment]
Indeed this got fixed with #26 now: https://pypi.org/project/clang-tidy/
