### ISSUE TITLE
pre-commit support

### ISSUE THREAD

**Issue by miki725** [ssciwr/clang-tidy-wheel#23]
In the PyPI package [description](https://pypi.org/project/clang-tidy/14.0.6/) there is a reference to a pre-commit mirror repository for running `clang-tidy`. I see its reference was removed in https://github.com/ssciwr/clang-tidy-wheel/commit/34e3b2520d640d4975f0012236fc6846ea53908b and that repo either does not exist yet or is not publicly available.

Is pre-commit compatibility still on the roadmap? If so, any help is needed to make that work?

**Comment by renefritze** [comment]
Using this wheel in a pre-commit setup is not my use case. 
The reference was there as a copy & paste artefact from clang-format-wheel. 
If you want to setup a repo to make clang-tidy wheel usable as a pre-commit hook, that would be great @miki725 :+1: 
Neither I, nor @dokempf currently plan to.
