### ISSUE TITLE
add support for arm wheel

### ISSUE THREAD

**Issue by miki725** [ssciwr/clang-tidy-wheel#24]
Does not look like any of the published wheels on PyPI support ARM which forces re-compilation of llvm. Any way to add ARM architecture support for wheels, similar to `clang-format`s:

```
clang_format-14.0.6-py2.py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
```

https://pypi.org/project/clang-format/#files

**Comment by miki725** [comment]
not sure if its as simple as uncommenting:

https://github.com/ssciwr/clang-tidy-wheel/blob/f89a8d00cef6e0f2b2ea3f44af8236b36012d29d/.github/workflows/release.yml#L41-L42

**Comment by renefritze** [comment]
> not sure if its as simple as uncommenting:

No, it's not :wink: 

We have [this](https://github.com/ssciwr/clang-tidy-wheel/issues/2) and [this](https://github.com/ssciwr/clang-tidy-wheel/issues/3) issue already and https://github.com/ssciwr/clang-tidy-wheel/pull/20 with https://github.com/ssciwr/clang-tidy-wheel/pull/20/commits/77b5ff433fb726af28558853452724b291d22d52 to the effect you described.

**Comment by miki725** [comment]
again, thank you for prompt response!
