### ISSUE TITLE
Publish v15.0.0

### ISSUE THREAD

**Issue by dokempf** [ssciwr/clang-tidy-wheel#26]
LLVM 15.0 released today. This should be the first proper release of the package. We should therefore wait for completion of #2, #3 and #17. If you need any support with these @renefritze, please let me know.

**Comment by renefritze** [comment]
Thanks for the offer @dokempf. I've been away on conferences basically the last three weeks and will be on vacation for a week from friday, so time has been especially sparse. I'll get to finalizing things inside the next 3 weeks.

**Comment by dokempf** [comment]
I don't think this is super-urgent at all, enjoy your holidays!

**Comment by renefritze** [comment]
[15.0.2 ongoing](https://github.com/ssciwr/clang-tidy-wheel/actions/runs/3486366812)

**Comment by renefritze** [comment]
Looks like there's [macos problems](https://github.com/ssciwr/clang-tidy-wheel/actions/runs/3486366812/jobs/5832765508)  
[Trying to fix that](https://github.com/ssciwr/clang-tidy-wheel/pull/31)

**Comment by renefritze** [comment]
https://pypi.org/project/clang-tidy/15.0.2/ but see #32
