### ISSUE TITLE
Version 15 does not build on macos arm

### ISSUE THREAD

**Issue by renefritze** [ssciwr/clang-tidy-wheel#32]
After encountering [this error](https://github.com/ssciwr/clang-tidy-wheel/actions/runs/3486366812/jobs/5832765508) I followed the guidance in [cibuildwheels docs](url) 

That still did not work however. 

So I've [disabled the arm variant](https://github.com/ssciwr/clang-tidy-wheel/pull/31) until someone with macOS knowledge can look into that.

**Comment by lkeegan** [comment]
llvm 15 added an optional dependency on libzstd (and by default enabled it if found) - from the linked macos build logs it looks like it is picking up and trying to bundle a version of this library which could be the cause of the issue:
```
  INFO:delocate.delocating:Copying library /usr/local/Cellar/zstd/1.5.2/lib/libzstd.1.5.2.dylib to clang_tidy/.dylibs/libzstd.1.5.2.dylib
```
Disabling libzstd in the cmake arguments when configuring llvm might be a fix
