### ISSUE TITLE
Publish V17

### ISSUE THREAD

**Issue by zainryan** [ssciwr/clang-tidy-wheel#53]
Hi there, thanks for maintaining this repo! Is it possible to publish v17 for clang-tidy so that it would match the [clang-format package](https://pypi.org/project/clang-format/)?

**Comment by renefritze** [comment]
I've triggered a test run for 17.0.1 https://github.com/ssciwr/clang-tidy-wheel/actions/runs/6325182840

**Comment by zainryan** [comment]
Much appreciated! Looks like there's a test error.

**Comment by renefritze** [comment]
> Looks like there's a test error.

Fails to install before packaging: https://github.com/ssciwr/clang-tidy-wheel/actions/runs/6325182840/job/17176161025#step:7:3864

I don't really have time to look into this. If you want to help out @zainryan you could try running cibuildwheel locally.

**Comment by renefritze** [comment]
Same happens for LLVM 16 already: https://github.com/ssciwr/clang-tidy-wheel/actions/runs/6335984417/job/17208151413#step:7:4007

**Comment by zainryan** [comment]
I created a pull request https://github.com/ssciwr/clang-tidy-wheel/pull/54 to fix this installation issue. Have tested it locally.

**Comment by zainryan** [comment]
Gentle ping :)

**Comment by renefritze** [comment]
Release workflow after merging #54 running now: https://github.com/ssciwr/clang-tidy-wheel/actions/runs/6407178599

**Comment by zainryan** [comment]
Thanks a lot!
