### ISSUE TITLE
Request to make clang-tidy path message suppressible

### ISSUE THREAD

**Issue by solarispika** [ssciwr/clang-tidy-wheel#64]
When clang-tidy is initialized, it prints out the full path of the clang-tidy binary being used.
https://github.com/ssciwr/clang-tidy-wheel/blob/ba761b1f05261e351b2daa6b828fb76a9693b667/clang_tidy/__init__.py#L14

I use clang-tidy in a CMake-based project where each source file is compiled and checked individually. This results in the path message being printed multiple times.

In addition, I use [matus-chochlik/ctcache](https://github.com/matus-chochlik/ctcache) to cache clang-tidy output. By default, ctcache will not cache clang-tidy output if anything is printed to stdout (see [here](https://github.com/matus-chochlik/ctcache/blob/b2aa2b3a8cd2ac9e39680a182be08abefb4a5b61/clang-tidy-cache#L1003-L1004)).

**Suggestion**: Could the path message be made suppressible, perhaps controlled by an environment variable or parameter? Alternatively, it could be moved to a debug/verbose mode. This would allow avoiding the repeated messages and enable better compatibility with ctcache.

**Comment by renefritze** [comment]
I think hiding the print behind sth like `CLANG_TIDY_WHEEL_VERBOSE=1` is entirely reasonable. It really was just a debug crutch for the binary finding for us, I think.
